### PR TITLE
Update SynapseTransfer.java

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@SupremeMortal Please fix conflicts... SynapseTransfer not work to compile..

**Comment by ghost** [comment]
@SupremeMortal Your plugin not work. For use /server on HUB or other need add plugin to nukkit....

**Comment by SupremeMortal** [comment]
@NycuRO This plugin will only need to be installed on the Nemisys server. (Proxy) At the moment the command does not work because of the issue described here:
https://github.com/iTXTech/Nemisys/issues/61

**Comment by SupremeMortal** [comment]
@NycuRO I'll implement a send command for the console till the bug is fixed

**Comment by ghost** [comment]
@SupremeMortal Yes,but other servers is different and plugin not loaded to HUB or Survival _for e.g._ , and HUB not have support for /server command. Need add plugin for HUB and Survival ,not for Nemisys because Nemisys isn't one server for players. It's one proxy server

**Comment by SupremeMortal** [comment]
@NycuRO A plugin on the proxy allows the command to be used on every Synapse Client connected to the Nemisys server

**Comment by ghost** [comment]
@SupremeMortal Ok :)

**Pull request merged**
